plugins {
	id 'fabric-loom' version '1.14-SNAPSHOT'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

tasks.withType(Copy).configureEach {
	// Only override during runData execution
	duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

base {
	archivesName = "${project.archives_base_name}-fabric-${project.minecraft_version}"
}

repositories {
	mavenLocal()

	maven {
		// Farmer's Delight Refabricated
		name = "Greenhouse Maven"
		url = 'https://repo.greenhouse.house/releases/'
	}

	maven { // Fabric ASM
		url = "https://jitpack.io/"
	}

	maven {
		// CraftTweaker, JEI
		name = "BlameJared"
		url = "https://maven.blamejared.com/"
	}
	maven { url "https://maven.ryanliptak.com/" } // AppleSkin
	maven { url = "https://maven.shedaniel.me/" } // REI and deps

	maven { url 'https://www.cursemaven.com' }
	maven { url = "https://maven.parchmentmc.org" }
}

fabricApi {
	configureDataGeneration() {
		client = true
	}
}

dependencies {
	// Minecraft
	minecraft "com.mojang:minecraft:${minecraft_version}"

	// Fabric
	modImplementation "net.fabricmc:fabric-loader:${loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}+${minecraft_version}"

	// Parchment mappings
	mappings loom.layered() {
		officialMojangMappings()
		parchment("org.parchmentmc.data:parchment-${minecraft_version}:${parchment_version}@zip")
	}

	// Farmer's Delight Refabricated
	modImplementation("vectorwing:FarmersDelight:${minecraft_version}-${farmersdelight_version}+refabricated") {
		exclude(group: "net.fabricmc")
	}

	// Cloth Config API
	modApi("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}") {
		exclude(group: "net.fabricmc.fabric-api")
	}

	// JEI
	//modLocalRuntime("mezz.jei:jei-${minecraft_version}-fabric:${jei_version}")
	//modLocalRuntime("me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}")

	// Appleskin
	modLocalRuntime("squeek.appleskin:appleskin-fabric:mc${minecraft_version}-${appleskin_version}")
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}