# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version = 1.21.6
minecraft_min_version = 1.21.6
minecraft_max_version = 1.21.6
loader_version = 0.18.4
parchment_version = 2025.06.29

# Mod Properties
mod_version = 1.5.0
maven_group = com.phantomwing.rusticdelight
archives_base_name = rusticdelight

# Dependencies
fabric_version = 0.128.2
appleskin_version = 3.0.6
farmersdelight_version = 3.2.3
cloth_config_version = 19.0.147

# JEI, not available for 1.21.4
#jei_version = 19.9.1.125
rei_version = 20.0.811